thresholds:
  nodes:
    DocumentNode: 0.5
    TermNode: 0.5
    EntityNode: 0.5
  edges:
    DocumentEdge: 0.5
    RelatedToEdge: 0.5
    ContainedInEdge: 0.5
    SynonymEdge: 0.5
    ContextEdge: 0.5
