defaults:
  db:
    location: localhost
    name: army_ant_test
    type: mongo
  eval:
    location: /opt/army-ant/eval
  jvm:
    memory: 5120

engines:
  gow-wikipedia:
    name: Wikipedia Data - Graph of Word
    message: >-
      Don't forget to launch Gremlin Server with the "gow_wikipedia" graph configured
      (e.g., "bin/gremlin-server.sh gremlin-server-neo4j.yaml").
    db:
      name: gow_wikipedia
    index:
      type: gow
      location: localhost:8182/gow_wikipedia

  gow-inex-10t-nl:
    name: INEX 10T-NL - Graph of Word
    message: >-
      Don't forget to launch Gremlin Server with the "gow_inex_10t_nl" graph configured
      (e.g., "bin/gremlin-server.sh gremlin-server-neo4j.yaml").
    db:
      name: gow_inex
    index:
      type: gow
      location: localhost:8182/gow_inex_10t_nl

  hgoe-inex-10t-nl:
    name: INEX 10T-NL - Hypergraph-of-Entity
    db:
      name: hgoe_inex
    index:
      type: hgoe
      location: /opt/army-ant/data/inex-10t-nl/hypergraph-of-entity
      preload: true
    ranking:
      default:
        id: random_walk
        params:
          l: 3
          r: 100
      functions:
        jaccard:
          name: Jaccard Score
        random_walk:
          name: Random Walk Score
          params:
            l: [1, 2, 3, 4, 5, 6]
            r: [10, 100, 250, 500, 750, 1000]

  hgoe-inex-dev:
    name: INEX Dev - Hypergraph-of-Entity
    db:
      name: hgoe_inex
    index:
      type: hgoe
      location: /opt/army-ant/data/inex-dev/hypergraph-of-entity
      preload: true
    ranking:
      default:
        id: random_walk
        params:
          l: 3
          r: 100
      functions:
        jaccard:
          name: Jaccard Score
        random_walk:
          name: Random Walk Score
          params:
            l: [1, 2, 3, 4, 5, 6]
            r: [10, 100, 250, 500, 750, 1000]
